[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/ethanpailes/pty-rs"]
git = "https://github.com/ethanpailes/pty-rs"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
